disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Patima's Portfolio"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

[params.author]
name = "Patima Poochai"
image = "images/pfp.png"
headline = "Linux, Cloud Computing, DevOps"
bio = "I'm an RHCSA and AWS-certified engineer with a background in IT, Linux administration, and computer science. I'm interested in designing, deploying, and securing computing infrastructure that helps people create a better world."
links = [
  { linkedin = "www.linkedin.com/in/patima-poochai808" },
  { github = "https://github.com/patimapoochai" },
  { dev = "https://dev.to/patimapoochai" },
  { mastodon = "https://infosec.exchange/@patlikestechnology" },
]

